config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tv_shows#index'
  resources :tv_shows do
    resources :episodes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :tv_show
end

app/models/film_location.rb
class FilmLocation < ApplicationRecord
  belongs_to :tv_show
end

app/models/nationality.rb
class Nationality < ApplicationRecord
    has_many :tv_shows, dependent: :destroy
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
    has_many :episodes
    validates :name, presence: true
    belongs_to :nationality
    has_many :film_locations, inverse_of: :tv_show
    accepts_nested_attributes_for :film_locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
    def create
        @tv_show = TvShow.find(params[:tv_show_id])
        @episode = @tv_show.episodes.create(episode_params)
        redirect_to tv_show_path(@tv_show)
    end

    private
    def episode_params
        params.require(:episode).permit(:episode_number, :title, :summary)
    end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :set_tv_show, only: %i[ show edit update destroy ]

  # GET /tv_shows or /tv_shows.json
  def index
    @tv_shows = TvShow.all
  end

  # GET /tv_shows/1 or /tv_shows/1.json
  def show
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
    2.times { @tv_show.film_locations.build }
  end

  # GET /tv_shows/1/edit
  def edit
  end


  # POST /tv_shows or /tv_shows.json
  def create
    @tv_show = TvShow.new(tv_show_params)
    @tv_show.nationality = Nationality.last || Nationality.find(params[:tv_show][:nationality_id])
    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to tv_show_url(@tv_show), notice: "Tv show was successfully created." }
        format.json { render :show, status: :created, location: @tv_show }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @tv_show.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /tv_shows/1 or /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to tv_show_url(@tv_show), notice: "Tv show was successfully updated." }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1 or /tv_shows/1.json
  def destroy
    @tv_show.destroy
    respond_to do |format|
      format.html { redirect_to tv_shows url, notice: "Tv show was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.find(params[:id])
    end  

    # Only allow a list of trusted parameters through.
    def tv_show_params
      params.require(:tv_show).permit(:name, :summary, :release_date, :rating)
    end
  
  def tv_show_params
    params.require(:tv_show).permit(
        :name, 
        :summary, 
        :release_date, 
        :rating, 
        :nationality_id,
        film_locations_attributes: [:id, :name, :indoor]
        )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFavoriteTvSeriesM9</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tv_shows/_form.html.erb
<%= form_with(model: tv_show) do |form| %>
  <% if tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>
      <ul>
        <% tv_show.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="container">
    <form class="form-horizontal" action="/action_page.php">
        <div class="form-group">
          <%= form.label :name, :class=>"cl control-label col-sm-2" %>
          <%= form.text_field :name, :class=>"fondo" %><br>
            
          <%= form.label :summary, :class=>"cl control-label col-sm-2" %>
          <%= form.text_area :summary, :class=>"fondo"  %><br>

          <%= form.label :release_date, :class=>"cl control-label col-sm-2" %>
          <%= form.date_select :release_date, :class=>"fondo"  %><br>
    
          <%= form.label :rating, :class=>"cl control-label col-sm-2" %>
          <%= form.text_field :rating, :class=>"fondo"  %><br>
          
          <div class= "cl text-justify">
          <%= collection_select(:tv_show, :nationality_id, Nationality.all, :id, :name, prompt: true) %><br>
          </div>
        </div>
  </form>  
</div>

<div class="container">
    <fieldset style="width:700px; higth:100px">
      <legend class="titulo">Film locations</legend>
      <ul class="form-check-input">
          <%= form.fields_for :film_locations do |film_locations_form| %>
            <li>
              <%= film_locations_form.label :name, :class=>"cl control-label col-sm-2"%>
              <%= film_locations_form.text_field :name, :class=>"fondo" %><br>

              <%= film_locations_form.label :indoor, :class=>"cl control-label col-sm-2" %>
              <%= film_locations_form.check_box :indoor, :class=>"fondo checkbox" %>
            </li>
          <% end %>
      </ul>
    </fieldset>
</div> 
  <br><br><br><br> <br><br><br><br><br><br><br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<br><br><br><br><br>
<div class="container">
<h1 class="titulo">Editing Tv Show</h1>
  <!-- Content here -->
  <%= render 'form', tv_show: @tv_show%>

<%= link_to  'Show', @tv_show, class: "btn btn-1"%> |
<%= link_to 'Back', tv_shows_path, class: "btn btn-2" %>
</div>

app/views/tv_shows/index.html.erb
<br><br><br><br><br>
<p id="notice"><%= notice %></p>
<h1 class="titulo">Tv Shows</h1>
<table>
  <thead class="table-dark text-center">
    <tr>
      <th >Name</th>
      <th >Summary</th>
      <th >Release date</th>
      <th >Rating</th>
      <th >Nacionality</th>
      <th ></th>
    </tr>
  </thead>
  <tbody class="table table-info table-bordered table">
    <% @tv_shows.each do |tv_show| %>
      <tr>
        <td><%= tv_show.name %></td>      
        <td><%= tv_show.summary %></td>      
        <td><%= tv_show.release_date %></td>     
        <td><%= tv_show.rating %></td>     
        <td><%= image_tag(url_for(tv_show.nationality.flag_img)) %></td>
        <td class="btn btn-1"><%= link_to 'Show', tv_show %></td>      
        <td class="btn btn-2"><%= link_to 'Edit', edit_tv_show_path(tv_show) %></td>
        <td class="btn btn-3"><%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Tv Show', new_tv_show_path, class: "btn btn-3" %>

app/views/tv_shows/new.html.erb
<br><br><br>
<div class="container">
<h1  class="titulo" style="width:700px">New Tv Show</h1>

<%= render 'form', tv_show: @tv_show %>

<%= link_to 'Back', tv_shows_path, class: "btn btn-2" %>
</div>


<!-- ...
<div class="container">
<div class="row">
  <div class="col-6">
<h1>New Tv Show</h1>
<br>
<h3>Ingrese un nuevo Tv Show</h3>

<%= form_with model: TvShow.new do |form| %>
  <div class="form-check">
    <%= form.label :name, "Name" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-check">
    <%= form.label :summary, "Summary" %>
    <%= form.text_area :summary, class: 'form-control' %>
  </div>
  <div class="form-check">
    <%= form.label :release_date, "Release Date" %>
    <%= form.date_field :release_date, class: 'form-control' %>
      </div>
  <div class="form-check">
    <%= form.label :rating, "Rating" %>
    <%= form.number_field :rating, step: '0.1', class: 'form-control'%>
  </div>
    <br>
    <%= form.submit  "Create Tv Show", class: "btn btn-info mt-3" %>
<% end %>
<br>

<%= link_to 'Back', tv_shows_path %> 
-->

app/views/tv_shows/show.html.erb
<br><br>
<div class="cont">
<p id="notice"><%= notice %></p>
<p>
  <strong class="cl">Name:</strong>     
  <%= @tv_show.name %>
</p> 

<p>
  <strong class="cl">Summary:</strong>     
  <%= @tv_show.summary %>
</p>
     
<p>
  <strong class="cl">Release date:</strong>      
  <%= @tv_show.release_date %>
</p>
      
<p>
  <strong class="cl">Rating:</strong>      
  <%= @tv_show.rating %>
</p>

<p>
    <strong class="cl">Nationality:</strong>
    <%= image_tag(url_for(@tv_show.nationality.flag_img)) %>
</p>
   
<p><strong class="cl">Film locations:</strong></p>

    <ul>
        <% if @tv_show.film_locations %>
            <% @tv_show.film_locations.each do |film_location|%>
                <li><strong><%= film_location.name %>: </strong>
                <%= film_location.indoor ? 'Indoor' : 'Outdoor' %></li>
            <% end %>
        <% else %>
            <% 'No Film Locations Added!!!'%>
        <% end %>
    </ul>

    <%= link_to 'Edit', edit_tv_show_path(@tv_show), class: "btn btn-2" %> |
    <%= link_to 'Back', tv_shows_path, class: "btn btn-3" %>
</div>

<hr class= "linea">

 <!-- ... -->
<div class="container">
    <h2>Agregue un episodio:</h2>
    <%= form_with model: [ @tv_show, @tv_show.episodes.build ] do |form| %>
        <p>
            <%= form.label :episode_number, :class=>"cl" %><br>
            <%= form.number_field :episode_number, :class=>"control-label col-sm-3" %>
        </p>
        <p>
            <%= form.label :title, :class=>"cl" %><br>
            <%= form.text_field :title, :class=>"control-label col-sm-3" %>
        </p>
        <p>
            <%= form.label :summary, :class=>"cl" %><br>
            <%= form.text_area :summary, :class=>"control-label col-sm-3" %>
        </p>
        <p>
            <%= form.submit "Crear episodio", class: "btn btn-1"%>
        </p>
    <% end %>
</div>

<hr class= "linea">

<!-- ... -->
<div class="container">
    <h2>Listado de episodios</h2><br>
    <% @tv_show.episodes.each do |episode| %>
        <p>
            <strong class="cl">Episode number:</strong>
            <%= episode.episode_number %>
        </p>

        <p>
            <strong class="cl">Title:</strong>
            <%= episode.title %>
        </p>

        <p>
            <strong class="cl">Summary:</strong>
            <%= episode.summary %>
        </p>
    <% end %>
</div>
<hr class= "linea">   